project:
  type: website

website:
  title: "Can.Do.So Books Dashboard"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: dashboard.qmd
        text: Dashboard

format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc: true



